### ISSUE TITLE
Error in segm.warp_cartilage_mask(image_data, n_of_cores) from segmentation_sa_ns

### ISSUE THREAD

**Issue by gillesdusfour** [sbonaretti/pyKNEEr#13]
I am trying to run the pykneer segmentation but I am receiving this error message when I try to run segm.warp_cartilage_mask(image_data, n_of_cores) from segmentation_sa_ns :

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\users\dusfour\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\dusfour\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\pykneer\segmentation_sa_for_nb.py", line 321, in warp_cartilage_mask_s
    mask = sitk.ReadImage(input_file_name)
  File "c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\SimpleITK\extra.py", line 346, in ReadImage
    return reader.Execute()
  File "c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\SimpleITK\SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file ".\preprocessed\01\registered\01_prep\invert\fc_rigidMask.mha" does not exist.
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-11-5776cba06c94> in <module>
----> 1 segm.warp_cartilage_mask(image_data, n_of_cores)

c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\pykneer\segmentation_sa_for_nb.py in warp_cartilage_mask(all_image_data, n_of_processes)
    328     start_time = time.time()
    329     pool = multiprocessing.Pool(processes=n_of_processes)
--> 330     pool.map(warp_cartilage_mask_s, all_image_data)
    331     print ("-> Warping completed")
    332     print ("-> The total time was %.2f seconds (about %d min)" % ((time.time() - start_time), (time.time() - start_time)/60))

c:\users\dusfour\appdata\local\programs\python\python38\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

c:\users\dusfour\appdata\local\programs\python\python38\lib\multiprocessing\pool.py in get(self, timeout)
    766             return self._value
    767         else:
--> 768             raise self._value
    769 
    770     def _set(self, i, obj):

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file ".\preprocessed\01\registered\01_prep\invert\fc_rigidMask.mha" does not exist.

**Comment by sbonaretti** [comment]
Hi! From the last line of your error, I read: `The file ".\preprocessed\01\registered\01_prep\invert\fc_rigidMask.mha" does not exist.` Did the previous steps work?

**Comment by gillesdusfour** [comment]
First I had an issue at step 4 segm.prepare_reference(image_data) which give me the following error :  

TypeError                                 Traceback (most recent call last)
<ipython-input-4-657d0eec349c> in <module>
----> 1 segm.prepare_reference(image_data)

c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\pykneer\segmentation_sa_for_nb.py in prepare_reference(all_image_data)
     70         image_data["current_anatomy"] = image_data["bone"]
     71         bone = elastix_transformix.bone()
---> 72         bone.prepare_reference (image_data)
     73 
     74         # instanciate cartilage class and prepare reference

c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\pykneer\elastix_transformix.py in prepare_reference(self, image_data)
     92         if not os.path.isfile(reference_mask_dil_name):
     93             mask    = sitk.ReadImage(reference_mask_name)
---> 94             maskDil = sitkf.dilate_mask(mask, radius)
     95             sitk.WriteImage(maskDil, reference_mask_dil_name)
     96 

c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\pykneer\sitk_functions.py in dilate_mask(mask, radius)
    352 
    353         mask     = sitk.Cast(mask,sitk.sitkInt16) # make sure that input of BinaryDilate is int
--> 354         mask_dil = sitk.BinaryDilate(mask,radius)#original
    355         # ~ mask_dil = sitk.BinaryDilate(mask)
    356         return mask_dil

c:\users\dusfour\appdata\local\programs\python\python38\lib\site-packages\SimpleITK\SimpleITK.py in BinaryDilate(*args, **kwargs)
  13021 def BinaryDilate(*args, **kwargs):
  13022     r"""BinaryDilate(Image image1, VectorUInt32 kernelRadius=std::vector< uint32_t >(3, 1), itk::simple::KernelEnum kernelType=sitkBall, double backgroundValue=0.0, double foregroundValue=1.0, bool boundaryToForeground=False) -> Image"""
> 13023     return _SimpleITK.BinaryDilate(*args, **kwargs)
  13024 class BinaryErodeImageFilter(ImageFilter):
  13025     r"""

TypeError: in method 'BinaryDilate', argument 2 of type 'std::vector< unsigned int,std::allocator< unsigned int > >'


Then I tried to modify the "dilate_mask" def from sitk_functions to bypass the previous error: 

def dilate_mask(mask,  radius):

	mask     = sitk.Cast(mask,sitk.sitkInt16) # make sure that input of BinaryDilate is int
	mask_dil = sitk.BinaryDilate(mask,radius)#original
	return mask_dil

I changed "mask_dil = sitk.BinaryDilate(mask,radius)" --> "mask_dil = sitk.BinaryDilate(mask)"

This way, I've been able to run to segm.warp_cartilage_mask(image_data, n_of_cores).

**Comment by twaungana** [comment]
I also encountered the same issue - I also modified the dilate_mask function but still ran into this error:

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file ".\preprocessed\01\registered\01_prep\invert\fc_rigidMask.mha" does not exist

Any suggestions?

**Comment by sbonaretti** [comment]
Should be solved with release 0.0.6.3
